#!/bin/bash
cd "$(dirname "$0")"
source venv/bin/activate

echo "========================================"
echo "  🎙️  Mac Whisperer - Voice Dictation  "
echo "========================================"
echo ""
echo "🚀 Starting with native macOS overlay..."
echo ""
echo "📍 Visual Overlay:"
echo "   • Real-time recording timer"
echo "   • Transcription status"
echo "   • LLM processing indicator"
echo "   • Text preview on completion"
echo "   • Location: bottom-right corner"
echo ""
echo "🎯 Controls:"
echo "   • Hold Cmd+Option to record"
echo "   • Release to transcribe"
echo "   • Text auto-types + copies to clipboard"
echo ""
echo "⚙️  Active Settings:"
echo "   • Model: small.en (high accuracy)"
echo "   • LLM grammar correction: enabled"
echo "   • Overlay: enabled"
echo ""
echo "Press Ctrl+C to stop"
echo "========================================"
echo ""
python whisper-dictation.py -m small.en -t 600
